export interface MenuSettings {
    log: boolean
    target: number
    look_at: boolean
    follow: boolean
    hidden: boolean
    cameraX: number
    cameraY: number
    cameraZ: number
    cameraUpX: number
    cameraUpY: number
    cameraUpZ: number
    zNear: number
    zFar: number
    posX: number
    posY: number
    posZ: number
    scaleX: number
    scaleY: number
    scaleZ: number
    psi: number
    theta: number
    phi: number
    targetX: number
    targetY: number
    targetZ: number
    fov: number
    frustum: boolean
    shadows: boolean
    bias: number
    lightPosX: number
    lightPosY: number
    lightPosZ: number
    lightTargX: number
    lightTargY: number
    lightTargZ: number
    lightFov: number
    spotlight: boolean
    lightWidth: number
    lightHeight: number
    lightNear: number
    lightFar: number
    lightUpX: number
    lightUpY: number
    lightUpZ: number
    currentobj: number
    draw: boolean
}