export interface MenuSettings {
    log: boolean
    target: number
    look_at: boolean
    follow: boolean
    hidden: boolean
    cameraX: number
    cameraY: number
    cameraZ: number
    cameraUpX: number
    cameraUpY: number
    cameraUpZ: number
    zNear: number
    zFar: number
    posX: number
    posY: number
    posZ: number
    scaleX: number
    scaleY: number
    scaleZ: number
    theta: number
    phi: number
    targetX: number
    targetY: number
    targetZ: number
    fov: number
    currentobj: number
    draw: boolean
}